# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MrErrorSan.ThinkVisionControl
PackageVersion: 0.0.1
MinimumOSVersion: 10.0.17763.0
InstallerType: portable
Commands:
- thinkvision-control
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/MrErrorSan/thinkvision-control/releases/download/v0.0.1/ThinkVisionControl.exe
  InstallerSha256: FC86E1D2C37F4E16158E5331B341DDECE66CF46CE37442CA9C0AC115CF1DFC4D
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
